In [42]:
import pandas as pd
df = pd.read_csv('cust_satisfaction.csv')
df

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,Male,Loyal Customer,Personal Travel,Eco Plus,neutral or dissatisfied,13,460,5,4,5,25,18.0
1,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,25,235,1,3,1,1,6.0
2,Female,Loyal Customer,Business travel,Business,satisfied,26,1142,5,4,5,0,0.0
3,Female,Loyal Customer,Business travel,Business,neutral or dissatisfied,25,562,2,3,2,11,9.0
4,Male,Loyal Customer,Business travel,Business,satisfied,61,214,3,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103899,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,23,192,2,4,2,3,0.0
103900,Male,Loyal Customer,Business travel,Business,satisfied,49,2347,5,5,4,0,0.0
103901,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,30,1995,4,4,4,7,14.0
103902,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,22,1000,1,1,1,0,0.0
103903,Male,Loyal Customer,Business travel,Business,neutral or dissatisfied,27,1723,1,4,1,0,0.0

In [43]:
df.drop_duplicates

<bound method DataFrame.drop_duplicates of         Gender      Customer Type   Type of Travel     Class  \
0         Male     Loyal Customer  Personal Travel  Eco Plus
1         Male  disloyal Customer  Business travel  Business
2       Female     Loyal Customer  Business travel  Business
3       Female     Loyal Customer  Business travel  Business
4         Male     Loyal Customer  Business travel  Business
...        ...                ...              ...       ...
103899  Female  disloyal Customer  Business travel       Eco
103900    Male     Loyal Customer  Business travel  Business
103901    Male  disloyal Customer  Business travel  Business
103902  Female  disloyal Customer  Business travel       Eco
103903    Male     Loyal Customer  Business travel  Business

                   satisfaction  Age  Flight Distance  Inflight entertainment  \
0       neutral or dissatisfied   13              460                       5
1       neutral or dissatisfied   25              235                       1
2                     satisfied   26             1142                       5
3       neutral or dissatisfied   25              562                       2
4                     satisfied   61              214                       3
...                         ...  ...              ...                     ...
103899  neutral or dissatisfied   23              192                       2
103900                satisfied   49             2347                       5
103901  neutral or dissatisfied   30             1995                       4
103902  neutral or dissatisfied   22             1000                       1
103903  neutral or dissatisfied   27             1723                       1

        Baggage handling  Cleanliness  Departure Delay in Minutes  \
0                      4            5                          25
1                      3            1                           1
2                      4            5                           0
3                      3            2                          11
4                      4            3                           0
...                  ...          ...                         ...
103899                 4            2                           3
103900                 5            4                           0
103901                 4            4                           7
103902                 1            1                           0
103903                 4            1                           0

        Arrival Delay in Minutes
0                           18.0
1                            6.0
2                            0.0
3                            9.0
4                            0.0
...                          ...
103899                       0.0
103900                       0.0
103901                      14.0
103902                       0.0
103903                       0.0

[103904 rows x 12 columns]>

In [44]:
df.drop_duplicates(inplace=True)

In [45]:
df.drop(['Age','Flight Distance','Gender'],inplace=True, axis = 1)

In [46]:
df

,Customer Type,Type of Travel,Class,satisfaction,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,Loyal Customer,Personal Travel,Eco Plus,neutral or dissatisfied,5,4,5,25,18.0
1,disloyal Customer,Business travel,Business,neutral or dissatisfied,1,3,1,1,6.0
2,Loyal Customer,Business travel,Business,satisfied,5,4,5,0,0.0
3,Loyal Customer,Business travel,Business,neutral or dissatisfied,2,3,2,11,9.0
4,Loyal Customer,Business travel,Business,satisfied,3,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...
103899,disloyal Customer,Business travel,Eco,neutral or dissatisfied,2,4,2,3,0.0
103900,Loyal Customer,Business travel,Business,satisfied,5,5,4,0,0.0
103901,disloyal Customer,Business travel,Business,neutral or dissatisfied,4,4,4,7,14.0
103902,disloyal Customer,Business travel,Eco,neutral or dissatisfied,1,1,1,0,0.0
103903,Loyal Customer,Business travel,Business,neutral or dissatisfied,1,4,1,0,0.0

In [47]:
print(df['Type of Travel'].unique())
df['satisfaction'].unique()
df['Class'].unique()

['Personal Travel' 'Business travel']

array(['Eco Plus', 'Business', 'Eco'], dtype=object)

In [48]:
dct = {
  'Loyal Customer':1, 'disloyal Customer':0
}
dct1 = {
  'Personal Travel':1, 'Business travel':0
}
dct2= {
  'satisfied':1, 'neutral or dissatisfied':0
}

dict3 = {
  'Eco':2, 'Eco Plus':0, 'Business':1}

print(dct2)
print(dict3)

{'satisfied': 1, 'neutral or dissatisfied': 0}
{'Eco': 2, 'Eco Plus': 0, 'Business': 1}

In [49]:
df.dropna(inplace=True)
df['Customer Type']=df['Customer Type'].map(dct)
df['Type of Travel']=df['Type of Travel'].map(dct1)
df['satisfaction']=df['satisfaction'].map(dct2)
df['Class']=df['Class'].map(dict3)
df.columns

Index(['Customer Type', 'Type of Travel', 'Class', 'satisfaction',
       'Inflight entertainment', 'Baggage handling', 'Cleanliness',
       'Departure Delay in Minutes', 'Arrival Delay in Minutes'],
      dtype='object')

In [50]:
df.head()

x=df.drop('Customer Type', axis=1)

y=df['Customer Type']

#we have to tell customer type-loyal disloyal

print(df)
# df.columns

        Customer Type  Type of Travel  Class  satisfaction  \
0                   1               1      0             0
1                   0               0      1             0
2                   1               0      1             1
3                   1               0      1             0
4                   1               0      1             1
...               ...             ...    ...           ...
103899              0               0      2             0
103900              1               0      1             1
103901              0               0      1             0
103902              0               0      2             0
103903              1               0      1             0

        Inflight entertainment  Baggage handling  Cleanliness  \
0                            5                 4            5
1                            1                 3            1
2                            5                 4            5
3                            2                 3            2
4                            3                 4            3
...                        ...               ...          ...
103899                       2                 4            2
103900                       5                 5            4
103901                       4                 4            4
103902                       1                 1            1
103903                       1                 4            1

        Departure Delay in Minutes  Arrival Delay in Minutes
0                               25                      18.0
1                                1                       6.0
2                                0                       0.0
3                               11                       9.0
4                                0                       0.0
...                            ...                       ...
103899                           3                       0.0
103900                           0                       0.0
103901                           7                      14.0
103902                           0                       0.0
103903                           0                       0.0

[103422 rows x 9 columns]

In [51]:

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

x_train.columns

Index(['Type of Travel', 'Class', 'satisfaction', 'Inflight entertainment',
       'Baggage handling', 'Cleanliness', 'Departure Delay in Minutes',
       'Arrival Delay in Minutes'],
      dtype='object')

In [52]:
#appplying model - classification

from sklearn.linear_model import LinearRegression
lr = LinearRegression()

lr.fit(x_train, y_train)


lr.score(x_train, y_train)
lr.score(x_test, y_test)
lr.predict(x_test)


import joblib
#object nm , "model.lb" -------> saved model
model = joblib.dump(lr, "custmodel.lb") 

model = joblib.load("custmodel.lb")
predlr=model.predict(x_test)
print(predlr)

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(x_train, y_train)
rf.score(x_train, y_train)
rf.score(x_test, y_test)
rf.predict(x_test)

import joblib
#object nm , "model.lb" -------> saved model
model = joblib.dump(rf, "custmodel1.lb")
model = joblib.load("custmodel1.lb")
pred=model.predict(x_test)

pred

for(i,j) in zip(pred, y_test):
    print(i,j)

[0.95117138 0.86540245 0.65803302 ... 0.52854148 0.91385955 1.01911214]
1 1
1 1
0 1
1 1
1 1
1 1
0 1
1 0
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 0
0 0
1 0
1 1
1 1
1 1
1 1
1 1
1 1
0 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
0 0
1 1
0 0
1 1
0 0
1 1
1 1
1 1
1 1
0 0
0 0
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 0
1 0
1 1
0 0
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
0 0
1 1
0 0
1 1
0 0
1 1
0 0
1 1
1 1
0 1
1 1
1 1
1 1
1 1
0 0
1 1
0 0
0 0
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 0
1 1
1 1
1 1
1 0
1 0
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
0 1
1 1
1 0
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
0 0
1 1
1 1
1 1
0 0
1 1
1 0
0 1
1 0
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
0 0
0 0
0 0
1 1
0 1
1 1
1 1
0 1
1 1
0 1
0 0
1 1
1 1
0 0
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
0 1
1 1
1 1
1 0
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
0 0
1 0
1 1
1 1
1 1
0 0
1 1
1 1
1 1
0 0
1 1
1 1
0 1
1 1
0 1
0 0
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 0
0 1
1 0
0 1
0 0
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
0 1
0 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
0 0
0 0
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
0 0
1 1
1 1
0 0
1 1
1 1
1 1
0 0
0 0
1 1
1 1
1 1
1 1
0 0
1 1
0 1
1 0
1 1
1 1
1 1
1 1
1 1
1 0
0 0
1 1
1 1
0 1
0 0
0 1
0 0
1 1
0 0
1 1
1 1
1 1
1 1
1 1
0 0
0 0
1 1
1 1
0 0
0 1
1 1
0 0
1 1
0 0
1 1
1 1
0 1
1 1
1 1
0 0
0 0
1 1
1 1
1 1
0 1
0 0
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
0 0
1 1
1 1
0 0
1 1
1 1
0 0
1 0
0 0
0 0
1 1
1 1
1 1
0 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
0 1
1 1
0 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
0 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
0 1
0 0
1 1
1 1
1 1
0 0
0 0
0 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
0 0
0 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 0
1 1
1 1
1 1
0 0
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
0 0
1 1
1 1
0 0
1 1
1 1
1 0
1 1
0 0
0 1
0 0
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
0 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
0 0
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
0 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
0 0
1 1
0 0
1 1
1 1
1 1
1 1
0 1
1 1
1 1
0 0
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 0
0 0
1 0
0 0
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
0 0
1 1
1 1
1 1
1 0
1 1
1 1
0 0
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
0 0
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
0 0
1 1
1 0
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
0 0
1 0
0 0
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
0 0
1 1
1 1
1 1
1 1
0 0
1 0
1 1
0 0
1 1
1 0
1 1
0 0
1 1
1 0
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
0 1
1 1
0 0
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 0
0 0
1 1
1 1
0 1
0 0
0 0
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
0 1
1 1
0 0
1 1
1 1
1 1
1 1
0 0
1 1
0 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
0 1
1 1
0 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
0 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
0 0
0 0
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 0
1 1
0 0
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 0
1 1
0 0
0 0
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
0 1
1 1
1 1
1 1
1 0
0 0
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
0 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
0 0
1 1
0 0
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 0
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
0 0
1 1
0 0
1 1
0 0
1 1
1 1
1 1
0 0
1 1
0 0
1 1
1 1
1 1
1 1
1 1
0 1
0 0
1 1
0 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 0
0 0
1 1
1 1
1 1
1 1
1 0
1 0
0 0
1 1
0 0
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
0 0
1 1
0 0
1 1
1 0
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
0 0
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
0 0
0 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
0 0
0 1
0 1
1 0
0 0
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
0 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 0
0 0
1 1
1 1
0 1
1 1
0 0
1 0
1 1
1 1
1 1
0 1
0 0
1 1
1 1
1 1
0 0
1 0
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 0
0 0
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
0 0
1 1
1 0
0 0
0 0
1 1
1 1
0 0
1 1
0 1
0 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
0 0
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 0
0 0
0 0
1 1
1 1
1 1
1 1
1 0
1 1
0 0
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
0 0
1 0
0 0
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
0 0
1 1
0 0
0 0
1 1
0 0
1 1
1 1
0 0
1 1
1 1
1 1
0 0
1 0
1 1
1 1
0 1
1 1
1 1
1 1
1 1
0 0
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
0 0
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
0 0
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
0 0
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
0 1
0 0
1 1
1 1
1 1
0 0
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
0 0
1 1
1 1
0 0
1 1
0 0
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 0
1 0
0 0
1 1
1 1
1 1
1 1
1 0
1 1
1 0
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
0 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
0 0
1 1
0 0
0 0
1 0
0 0
1 1
0 0
1 1
0 0
0 1
1 1
1 1
1 1
0 0
1 1
0 0
1 1
1 1
1 1
0 1
1 1
0 1
1 1
1 1
1 1
1 1
0 0
1 1
1 0
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
0 0
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
0 0
0 0
1 1
0 0
0 0
1 1
1 1
1 1
0 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
0 0
1 1
1 0
0 0
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
0 1
0 1
1 1
0 1
1 1
0 1
1 1
1 1
1 1
1 1
0 1
0 1
1 1
1 1
1 1
0 0
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
0 0
0 1
0 0
1 1
1 0
1 1
1 1
1 0
1 1
0 0
0 0
1 1
1 1
0 0
1 1
0 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
0 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
0 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
0 0
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
0 0
0 0
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 0
1 0
1 1
1 1
1 1
1 1
1 1
0 0
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
0 1
0 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
0 0
1 1
0 0
1 1
0 0
1 1
0 0
0 0
1 1
1 1
1 1
1 1
0 0
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
0 0
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 0
0 0
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
0 0
0 0
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
0 0
1 1
1 1
1 1
0 1
1 1
0 0
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
0 0
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
0 0
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
0 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
0 0
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 0
0 1
0 0
1 0
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
0 0
1 1
1 1
1 0
1 1
1 1
0 0
1 1
1 1
1 1
1 0
1 1
1 1
0 1
0 1
1 0
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
0 1
1 0
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 0
1 1
1 1
1 1
0 0
1 1
0 1
0 0
1 1
0 0
1 1
0 1
0 0
1 1
0 1
1 0
0 0
1 1
1 1
1 0
0 0
1 1
1 1
1 1
1 1
1 1
1 0
1 1
0 0
1 1
1 0
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 0
1 1
0 1
0 0
1 0
1 1
1 0
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
0 0
1 1
0 0
0 0
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
0 0
1 1
0 0
0 1
1 1
1 1
0 0
1 1
1 1
1 1
1 0
1 1
1 1
1 1
0 0
1 1
1 1
0 1
0 0
1 1
1 1
1 1
0 0
1 1
0 0
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
0 0
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 0
1 1
1 0
1 1
1 1
1 1
1 0
0 0
0 1
1 1
0 1
0 0
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 0
1 1
1 1
1 0
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 0
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
0 0
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
0 0
1 1
1 0
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 0
0 0
1 1
0 1
1 1
1 1
1 0
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 0
1 1
0 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
0 0
0 0
0 1
1 1
1 1
0 1
0 0
1 1
1 1
1 1
1 0
1 1
1 1
1 1
0 0
1 1
0 0
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
0 0
1 1
0 1
1 1
1 1
0 0
0 0
1 1
1 0
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
0 0
0 0
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 0
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
0 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 0
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
0 0
1 1
1 1
0 1
0 0
1 1
1 1
1 1
1 1
0 1
1 0
1 1
1 1
1 0
1 1
1 1
1 1
1 1
0 0
0 0
1 1
1 1
1 1
1 1
1 1
0 0
1 1
0 0
1 1
1 1
1 1
0 0
0 0
0 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 0
0 0
0 1
1 1
1 1
1 0
0 0
1 1
1 0
1 1
1 1
1 1
1 0
1 0
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
0 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
0 0
1 1
0 0
1 1
0 0
1 1
1 1
1 1
1 1
1 0
1 1
0 0
0 0
1 1
1 0
0 0
1 1
1 1
1 1
1 1
0 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
0 0
0 0
1 1
1 1
0 0
0 1
0 0
1 1
1 1
1 1
1 1
0 1
0 0
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
0 0
1 1
1 1
1 1
1 1
0 1
1 1
0 0
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 0
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 0
1 1
1 1
1 0
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
0 1
1 0
1 1
1 1
0 1
1 1
1 1
0 0
0 0
1 1
1 1
1 1
1 0
1 1
0 0
1 1
1 1
1 0
1 1
1 1
1 1
0 0
1 1
0 1
1 1
1 1
1 1
0 0
0 0
1 1
1 1
0 0
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
0 0
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
0 0
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 0
0 0
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
0 1
1 1
1 1
0 0
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
0 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 0
0 0
1 1
0 0
1 1
1 1
1 1
0 0
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 0
0 1
1 1
1 1
0 1
1 1
1 1
1 1
0 0
0 0
0 0
1 1
1 1
0 0
1 1
1 1
1 0
1 1
1 1
1 1
0 0
1 1
1 1
1 1
0 0
1 1
0 1
0 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
0 1
1 0
1 1
1 1
1 0
1 1
0 1
1 1
1 1
1 1
0 0
1 1
0 1
1 1
1 1
1 1
1 0
1 1
1 0
1 1
1 1
1 1
0 0
0 0
1 1
0 0
1 1
0 0
1 1
0 0
1 1
1 1
0 0
0 0
1 1
1 1
0 0
1 1
1 0
1 1
1 1
1 1
1 1
1 0
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
0 1
0 0
1 1
1 1
1 1
1 1
1 1
0 0
0 1
0 0
0 0
1 1
0 0
0 0
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
0 0
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
0 0
1 1
1 0
0 0
0 1
1 1
0 0
1 1
1 1
1 1
1 0
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
0 0
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
0 0
1 1
1 1
1 0
0 0
1 1
1 1
1 0
1 0
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
0 0
1 1
0 0
1 1
1 0
1 1
1 1
1 0
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
0 0
1 1
0 0
1 1
0 0
1 1
1 1
1 1
1 1
0 0
0 0
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
0 0
1 1
0 1
1 1
1 0
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 0
1 1
0 0
1 1
1 1
0 0
1 1
1 1
1 1
0 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 0
1 1
1 1
0 0
1 1
0 0
0 0
1 1
0 0
0 0
0 0
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
0 0
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
0 0
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
0 1
1 1
0 1
1 1
1 1
0 0
1 1
1 1
1 1
0 0
1 1
0 0
1 1
0 0
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
0 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 0
0 0
0 0
1 1
1 0
1 1
0 1
0 0
1 1
1 0
1 0
1 1
1 1
1 0
0 1
1 0
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
0 0
0 1
1 1
1 1
1 1
1 1
0 0
1 1
0 0
1 1
1 1
0 0
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
0 0
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
0 0
1 0
1 1
0 0
1 1
1 1
1 1
0 0
0 0
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
0 0
1 1
0 0
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
0 0
1 1
1 1
1 0
0 1
0 0
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
0 0
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
0 1
0 0
1 1
1 1
1 1
1 0
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
0 0
1 0
0 0
1 1
0 0
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
0 0
1 0
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 0
0 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
0 0
0 0
1 1
1 1
0 0
0 0
1 1
0 0
0 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 0
0 1
1 1
1 1
0 0
1 1
0 0
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 0
0 1
0 0
1 1
1 1
1 1
1 1
0 0
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
0 0
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
0 0
1 1
1 0
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
0 1
0 0
1 0
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
0 1
1 0
1 1
1 1
0 0
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
0 0
1 1
1 1
0 1
0 0
1 1
1 1
1 0
1 0
1 1
1 1
1 1
1 0
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
0 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
0 1
0 0
1 1
1 1
0 0
1 1
1 1
0 0
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 0
1 1
1 1
1 1
0 0
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
0 0
0 0
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 0
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
0 1
1 1
1 1
1 1
0 1
0 0
1 1
1 1
1 1
1 0
1 1
1 1
1 1
0 1
0 0
1 1
1 1
1 1
0 0
0 0
1 1
0 0
0 1
1 1
1 1
1 1
1 1
0 0
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
0 0
1 0
1 1
1 0
1 1
1 1
1 0
1 0
0 0
1 1
1 1
1 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
0 1
1 1
1 1
1 1
1 0
1 1
1 0
0 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
0 0
1 0
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 1
1 1
0 0
1 0
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 0
0 0
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 1
1 1
0 1
1 1
1 1
1 1
0 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 0
1 0
1 1
1 1
1 1
0 0
1 1
1 1
1 1
0 0
1 1
0 0
1 1
0 0
1 1
0 0
1 1
1 1
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1

In [53]:
rf.score(x_test, y_test)

0.9018129079042785

In [ ]:
from  sklearn.svm import SVC  #suport vector clasifier

sv= SVC()
sv.fit(x_train,y_train)

In [ ]:
sv.score(x_train,y_train)
sv.score(x_test,y_test)
pred=sv.predict(x_test)
pred


# //consuion matric-how much it will confuse

KeyboardInterrupt:

In [ ]:
#sample function
#bar btwn loyal an dinloyal - imabalance data (sample)
# if data is balance acu>95%